-- -------------------------------------------------------------------
-- @2020, Odysseus Data Services, Inc. All rights reserved
-- MIMIC IV CDM Conversion
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- dependency, run after:
--      st_core.sql
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- A draft to apply Wave Forms

-- (Manlik) Regardless of what format we end up with - is to take the meta data and map them into:

-- Procedure
-- [SNOMED.4141651] Continuous ECG monitoring
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- procedure_source_value = "<wfdb reference ID - ex 3700002_0011>"

-- Device_exposure
-- [SNOMED.45758393] Patient monitoring system module, electrocardiographic
-- device_exposure_start_datetime is the date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- device_exposure_end_datetime is the start + total duration of the monitor data
-- device_source_value = "<wfdb reference ID - ex 3700002_0011>"

-- Measurement - heart rate (1 to N), original WFDB reported or generated by our ETL
-- [SNOMED.4239408] Heart rate - units [SNOMED.4118124] bpm
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given)
-- measurement_source_value = "<wfdb reference ID>.<algorithm ID> - ex "3700002_0011.WFDB" or "3700002_0011.CCSIMxv1"

-- Measurement - P-QRS-T derived measurements - aVF R-wave example
-- [LOINC.3022916] R wave amplitude in lead AVF
-- date/time is offset from start of monitor (1/1/1990 if no actual time is given) + segment offset
-- measurement_source_value = "<wfdb reference ID>.<algorithm ID> - ex 3700002_0011.CCSIMxv1"

-- I have ECG measurement map down to lead level

-- The same approach would apply to BP and Respiratory values.

-- If we derive observations like AFib and Tachycardia - we can further map these to the condition_occurrence table as [4064452] ECG: atrial fibrillation using the same reference time and source
--
-- parsed codes targeted to clinical findings, target cdm table - cdm_condition_occurrence
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- open points:
--      parse XML to create src_* or raw_* tables

-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- staging tables
-- -------------------------------------------------------------------

-- -------------------------------------------------------------------
-- src_waveform_header
-- -------------------------------------------------------------------

DROP TABLE IF EXISTS @etl_database.@etl_schema.src_waveform_header CASCADE;

CREATE TABLE @etl_database.@etl_schema.src_waveform_header
(
    reference_id            VARCHAR(255),
    raw_files_path          TEXT,
    case_id                 BIGINT,
    subject_id              BIGINT,
    start_datetime          TIMESTAMP,
    end_datetime            TIMESTAMP,
    --
    load_table_id           VARCHAR(255),
    load_row_id             BIGINT,
    trace_id                TEXT
);

-- parsed codes to be targeted to table cdm_measurement

DROP TABLE IF EXISTS @etl_database.@etl_schema.src_waveform_mx CASCADE;

CREATE TABLE @etl_database.@etl_schema.src_waveform_mx
(
    case_id                 BIGINT,  -- FK to the header
    segment_name            VARCHAR(255), -- two digits of case_id, 5 digits of internal sequence number
    subject_id              BIGINT,  -- patient's id
    reference_id            VARCHAR(255), -- file name without extension
    mx_datetime             TIMESTAMP, -- time of measurement
    source_code             VARCHAR(255),   -- type of measurement
    value_as_number         DOUBLE PRECISION,
    unit_source_value       VARCHAR(100), -- measurement unit "BPM", "MS", "UV" (microvolt) etc.
                                         -- map these labels and populate unit_concept_id
    --
    load_table_id           VARCHAR(255),
    load_row_id             BIGINT,
    trace_id                TEXT
);


-- parse xml from Manlik? -> src_waveform
-- src_waveform -> visit_detail (visit_detail_source_value = <reference ID>)

-- finding the visit
-- create visit_detail
-- create measurement -> link visit_detail using visit_detail_source_value = meas_source_value
-- (start with Manlik's proposal)


-- -------------------------------------------------------------------
-- insert sample data
-- -------------------------------------------------------------------


INSERT INTO @etl_database.@etl_schema.src_waveform_header
SELECT
    subj.short_reference_id             AS reference_id,
    subj.long_reference_id              AS raw_files_path,
    subj.case_id::BIGINT                AS case_id,
    subj.subject_id::BIGINT             AS subject_id,
    src.start_datetime::TIMESTAMP       AS start_datetime,
    src.end_datetime::TIMESTAMP         AS end_datetime,
    --
    'wf_header'                         AS load_table_id,
    0                                   AS load_row_id,
    json_build_object(
        'subject_id', subj.subject_id,
        'reference_id', subj.short_reference_id
    )::TEXT                             AS trace_id
FROM
    @wf_database.@wf_schema.wf_header subj
INNER JOIN
    (
        SELECT
            case_id,
            MIN(date_time) AS start_datetime,
            MAX(date_time) AS end_datetime
        FROM @wf_database.@wf_schema.wf_details
        GROUP BY case_id
    ) src
        ON src.case_id = subj.case_id
;


INSERT INTO @etl_database.@etl_schema.src_waveform_mx
SELECT
    src.case_id::BIGINT                 AS case_id, -- FK to the header
    src.segment_name::VARCHAR(255)      AS segment_name,
    subj.subject_id::BIGINT             AS subject_id,
    subj.short_reference_id             AS reference_id,
    src.date_time::TIMESTAMP            AS mx_datetime,
    src.src_name                        AS source_code,
    src.value::DOUBLE PRECISION         AS value_as_number,
    unit_concept_name                   AS unit_source_value,
    --
    'wf_details'                        AS load_table_id,
    abs(hashtext(gen_random_uuid()::TEXT)) AS load_row_id,
    json_build_object(
        'case_id', src.case_id,
        'date_time', src.date_time::TEXT,
        'src_name', src.src_name
    )::TEXT                             AS trace_id
FROM
    @wf_database.@wf_schema.wf_details src
INNER JOIN
    @wf_database.@wf_schema.wf_header subj
        ON src.case_id = subj.case_id
;